### ISSUE TITLE
Managed configuration for network mainnet_candidate_4 does not exist

### ISSUE THREAD

**Issue by islishude** [input-output-hk/cardano-rest#61]
version: 2.1.0 by docker

```yaml
  submit-api:
    image: inputoutput/cardano-submit-api:2.1.0
    environment:
      - NETWORK=mainnet_candidate_4
    depends_on:
      - node
    volumes:
      - /data/ada-shelley-testnet/socket:/node-ipc
    ports:
      - 8101:8101
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
```

node config: https://github.com/input-output-hk/cardano-db-sync/issues/206
