### ISSUE TITLE
cardano-rest explorer api connect postgres failed

### ISSUE THREAD

**Issue by wshhz** [input-output-hk/cardano-rest#71]
# Context
 
 

| Information  | -                                                     |
| ---          | ---                                                   |
| Version      | v2.1.1 |
| Platform     | Docker |
| Installation | From Dockerhub |

# Steps to Reproduce

1. new`docker-compose.yml`:
```
version: "3.5"

services:
  # pg数据库镜像
  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - /data/ada/data/${NETWORK}_postgres:/var/lib/postgresql/data
    restart: on-failure

  # 节点镜像
  cardano-node:
    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-1.18.0}
    environment:
      - NETWORK=${NETWORK}
    volumes:
      - /data/ada/data/node-${NETWORK}-db:/data
      - node-ipc:/ipc
      - node-config:/nix/store

  # 钱包镜像
  cardano-wallet:
    image: inputoutput/cardano-wallet:latest
    volumes:
      - /data/ada/data/wallet-${NETWORK}-db:/wallet-db
      - node-ipc:/ipc
      - node-config:/config
    ports:
      - 8090:8090
    entrypoint: []
    command: bash -c "
        ([[ $$NETWORK == \"mainnet\" ]] && $$CMD --mainnet) ||
        ([[ $$NETWORK == \"testnet\" ]] && $$CMD --testnet /config/*-$$NETWORK-byron-genesis.json)
      "
    environment:
      CMD: "cardano-wallet-shelley serve --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0"
      NETWORK:
    restart: on-failure

  # 浏览器使用的同步数据库镜像
  cardano-db-sync:
    image: inputoutput/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-3.1.0}
    environment:
      - NETWORK=${NETWORK}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - cardano-node
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - node-ipc:/node-ipc
    restart: on-failure

  # 浏览器api镜像
  cardano-explorer-api:
    image: inputoutput/cardano-explorer-api:${CARDANO_EXPLORER_API_VERSION:-2.1.1}
    depends_on:
      - postgres
      - cardano-db-sync
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    ports:
      - 8100:8100
    restart: on-failure

secrets:
  postgres_db:
    file: /data/ada/config/postgres_db
  postgres_password:
    file: /data/ada/config/postgres_password
  postgres_user:
    file: /data/ada/config/postgres_user

volumes:
  postgres:
  node-ipc:
  node-config:
```

2. use`NETWORK=testnet docker-compose up -d`

3. use`docker logs -f ada_cardano-explorer-api_1` see log:
```
Generating PGPASS file
cardano-explorer-api: libpq: failed (could not connect to server: Connection refused
	Is the server running on host "postgres" (192.168.208.4) and accepting
	TCP/IP connections on port 5432?
)
[Info] Connecting to database at postgres:5432
[Info] Connecting to database at postgres:5432
cardano-explorer-api: libpq: failed (could not connect to server: Connection refused
	Is the server running on host "postgres" (192.168.208.4) and accepting
	TCP/IP connections on port 5432?
)
```

## Expected behavior

success run
